config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: "admin/admins/sessions",
  }
  
  namespace :admin do
    root to: "dashboards#top"
    resources :users, only: [:index, :destroy]
    resources :categories, only: [:index, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    devise_for :users, skip: [:password], controllers: {
      sessions: "public/users/sessions",
      registrations: "public/users/registrations",
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :posts do
      collection do
        resources :ranks, only: [:index]
      end
      resources :comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    resources :animals, only: [:show, :edit, :update, :new, :create, :destroy]

    resources :users, only: [:index, :show] do
      resources :animals, only: [:index]
      resources :favorites, only: [:index]
      resource :relationships, only: [:create, :destroy]
      # resources :following_users, only: [:index]
      # resources :followed_users, only: [:index]
      get "following_users" => "relationships#following", as: "following"
      get "followed_users" => "relationships#followed", as: "followed"
    end

    resources :categories, only: [:create, :index, :show]
  end
end

app/models/user.rb
class User < ApplicationRecord
  GUEST_USER_EMAIL = "guest@example.com"
  private_constant :GUEST_USER_EMAIL

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :recoverable, :rememberable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :animals, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :active_relationships, class_name: "Relationship", foreign_key: "following_user_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_user_id", dependent: :destroy
  has_many :following_users, through: :active_relationships, source: :followed_user
  has_many :followed_users, through: :passive_relationships, source: :following_user

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  scope :user_search, -> (name) do
    where("name LIKE ?", "%#{sanitize_sql_like(name)}%")
  end

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image/jpg", content_type: "image/jpg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def follow(user)
    active_relationships.create(followed_user_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_user_id: user.id).destroy
  end

  def following?(user)
    following_users.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
    if params[:name].present?
      @users = @users.user_search(params[:name])
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
    redirect_to admin_users_path, notice: "ユーザーを削除しました。"
  end

end

app/controllers/user/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: "guestuserでログインしました。"
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]
  
  def index
    if params[:name].present?
      @users = User.where("name LIKE ?", "%#{params[:name]}%")
      @users = User.all if @users.empty?
    else
      @users = User.all
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def confirm
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
  
   def ensure_guest_user
     @user = User.find(params[:id])
     if @user.guest_user?
       redirect_to user_path(current_user)
     end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<% users.each do |user| %>
  <div>
    <%= link_to user_path(user) do %>
      <%= image_tag user.get_profile_image(100,100), class: "mt-3 rounded-circle"; %>
      <%= user.name %>
    <% end %>
  </div>
<% end %>

app/views/users/confirm.html.erb
<h1>Users#confirm</h1>
<p>Find me in app/views/users/confirm.html.erb</p>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <label for="introduction">Introduction</label>
  <%= f.text_area :introduction %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<%= form_with url: users_path, method: :get do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "検索" %>
<% end %>

<%= render 'user', user: @user %>

app/views/users/show.html.erb
<h2>ユーザー</h2>
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <p>introduction:<%= @user.introduction %></p>
</div>
  
  <% if current_user != @user %>
    <% if current_user.following?(@user) %>
      <%= link_to "フォロー外す", user_relationship_path(@user), method: :delete, class: "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(@user), method: :post, class: "btn btn-success" %>
    <% end %>
　<% end %>
　
　<div>フォロー数: 
　  <%= link_to user_following_path(@user) do %>
　    <%= @user.following_users.count %>
　  <% end %>
　 </div>
　<div>フォロワー数: 
　  <%= link_to user_followed_path(@user) do %>
　    <%= @user.followed_users.count %>
　  <% end %>
  </div>

  <% if @user == current_user %>
  <% unless @user.guest_user? %>
　  <%= link_to "プロフィール編集", edit_user_path %>
　  <%= link_to "お気に入り", user_favorites_path(@user) %>
  <% end %>
  <% end %>
  
<div>
  <%= link_to "動物一覧", user_animals_path(@user) %>
</div>

<h4>投稿一覧</h4>
<%= render 'posts/list', posts: @posts %>