config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: "admin/admins/sessions",
  }
  
  namespace :admin do
    root to: "dashboards#top"
    resources :users, only: [:index, :destroy]
    resources :categories, only: [:index, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    devise_for :users, skip: [:password], controllers: {
      sessions: "public/users/sessions",
      registrations: "public/users/registrations",
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :posts do
      collection do
        resources :ranks, only: [:index]
      end
      resources :comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    resources :animals, only: [:show, :edit, :update, :new, :create, :destroy]

    resources :users, only: [:index, :show] do
      resources :animals, only: [:index]
      resources :favorites, only: [:index]
      resource :relationships, only: [:create, :destroy]
      # resources :following_users, only: [:index]
      # resources :followed_users, only: [:index]
      get "following_users" => "relationships#following", as: "following"
      get "followed_users" => "relationships#followed", as: "followed"
    end

    resources :categories, only: [:create, :index, :show]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :animals
  has_many :category_posts, through: :animals, source: :posts

  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }

  scope :name_search, -> (name) do
    where("name LIKE ?", "%#{sanitize_sql_like(name)}%")
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  
  def index
    @categories = Category.all.page(params[:page])
    if params[:name].present?
      @categories = @categories.name_search(params[:name])
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
  
  def destroy
    category = Category.find(params[:id])
    category.destroy!
    redirect_to admin_categories_path, notice: "カテゴリーを削除しました。"
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      @categories = Category.all
      render :index
    end
  end
  
  def index
    @category = Category.new
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @posts = @category.category_posts
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 mx-auto max-w-480 shadow-lg rounded">
      <div class="h5 text-dark bg-light p-4 mb-0">カテゴリー編集</div>
      <div class="form-body p-4">
        <%= render partial: "shared/error_message", locals: { errors: @category.errors } %>
        
        <%= form_with model: [:admin, @category] do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          <%= f.submit "保存", class: "btn btn-outline-secondary mb-3" %>
        <% end %>

        <%= link_to admin_categories_path do %>
          <i class="fa-solid fa-arrow-left-long">戻る</i>
        <% end %>
      </div>
　　</div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="d-md-flex">
    <div class="h3 mr-5">カテゴリー</div>
    <%= form_with url: admin_categories_path, method: :get do |f| %>
      <%= f.text_field :name, value: params[:name], placeholder: "ユーザー名" %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
  <%= link_to admin_root_path do %>
    <i class="fa-solid fa-arrow-left-long">戻る</i>
  <% end %>
  
  <div class="row">
    <div class="col-md-5 col-sm-10 mt-3">
      <table class="table mt-3">
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <td>
              <%= category.name %>
            </td>
            <td>
              <%= link_to "編集", edit_admin_category_path(category), class: "btn btn-outline-secondary ml-5" %>
              <%= link_to "削除", admin_category_path(category), method: :delete, class: "btn btn-outline-danger ml-5", data: { confirm: "本当に削除しますか？" } %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @categories %>
    </div>
  </div>
</div>