config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: "admin/admins/sessions",
  }
  
  namespace :admin do
    root to: "dashboards#top"
    resources :users, only: [:index, :destroy]
    resources :categories, only: [:index, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    devise_for :users, skip: [:password], controllers: {
      sessions: "public/users/sessions",
      registrations: "public/users/registrations",
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :posts do
      collection do
        resources :ranks, only: [:index]
      end
      resources :comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    resources :animals, only: [:show, :edit, :update, :new, :create, :destroy]

    resources :users, only: [:index, :show] do
      resources :animals, only: [:index]
      resources :favorites, only: [:index]
      resource :relationships, only: [:create, :destroy]
      # resources :following_users, only: [:index]
      # resources :followed_users, only: [:index]
      get "following_users" => "relationships#following", as: "following"
      get "followed_users" => "relationships#followed", as: "followed"
    end

    resources :categories, only: [:create, :index, :show]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :animal_posts, dependent: :destroy
  has_many :animals, through: :animal_posts, source: :animal

  has_one_attached :image

  validates :image, presence: true
  validates :caption, presence: true, length: { maximum: 200 }

  scope :caption_search, -> (caption) do
    where("caption LIKE ?", "%#{sanitize_sql_like(caption)}%")
  end

  def get_image(width, height)
    if image.blob.variable?
      image.variant(resize_to_fit: [width, height]).processed
    else
      image
    end
  end

  def favorited_by?(user)
    favorites.any? { |fav| fav.user_id == user.id }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @post = Post.new
    @animals = current_user.animals
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      @animals = current_user.animals
      render :new
    end
  end

  def index
    if params[:caption].present?
      @posts = Post.where("caption LIKE ?", "%#{params[:caption]}%")
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
    @animals = current_user.animals
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      @animals = current_user.animals
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption, animal_ids: [])
  end

  def is_matching_login_user
    post = Post.find(params[:id])
    unless post.user_id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_list.html.erb
<% posts.each do |post| %>
  <div>
    <%= link_to post_path(post) do %>
      <%= image_tag post.get_image(200,200) %>
    <% end %>
    <p><%= post.caption %></p>
    <p><%= link_to post.user.name, user_path(post.user) %></p>
    <% if post.favorited_by?(current_user) %>
      <p>
        <%= link_to post_favorite_path(post), method: :delete do %>
        <i class="fa-solid fa-heart" style="color: red;"></i> <%= post.favorites.count %> いいね
        <% end %>
      </p>
    <% else %>
      <p>
        <%= link_to post_favorite_path(post), method: :post do %>
        <i class="fa-regular fa-heart" style="color: red;"></i> <%= post.favorites.count %> いいね
        <% end %>
      </p>
    <% end %>
        
    <p><%= link_to "#{post.comments.count} コメント", post_path(post) %></p>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿編集</h1>
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post do |f| %>
  <h4>本文</h4>
  <%= f.text_area :caption %>
  
  <%= f.label :animal_ids %>
    <div>
      <%= f.collection_check_boxes :animal_ids, @animals, :id, :name %>
    </div>
    
  <%= f.submit '保存' %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>

<%= form_with url: posts_path, method: :get do |f| %>
  <%= f.text_field :caption %>
  <%= f.submit "検索" %>
<% end %>

<%= link_to "カテゴリー", categories_path %>

<%= render 'list', posts: @posts %>

app/views/posts/new.html.erb
<h1>画像投稿フォーム</h1>
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>本文</h4>
  <%= f.text_area :caption %>

  <div>
    <%= f.label :animal_ids %>
    <div>
      <%= f.collection_check_boxes :animal_ids, @animals, :id, :name %>
    </div>
  </div>

  <%= f.submit '投稿' %>

<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
  <div>
    <%= image_tag @post.get_image(200,200) %>
    <p><%= @post.caption %></p>
    <p><%= link_to @post.user.name, user_path(@post.user.id) %></p>
    <p><%= @post.created_at.strftime('%Y/%m/%d') %></p>
    
    <% if @post.user == current_user %>
      <%= link_to "編集", edit_post_path %>
      |
      <%= link_to "削除", post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
    <% end %>
    
    
    <% if @post.favorited_by?(current_user) %>
      <p>
        <%= link_to post_favorite_path(@post), method: :delete do %>
        <i class="fa-solid fa-heart" style="color: red;"></i> <%= @post.favorites.count %> いいね
        <% end %>
      </p>
      <% else %>
      <p>
        <%= link_to post_favorite_path(@post), method: :post do %>
        <i class="fa-regular fa-heart" style="color: red;"></i> <%= @post.favorites.count %> いいね
        <% end %>
      </p>
    <% end %>
    
    <div>
      <p>コメント件数：<%= @post.comments.count %></p>
      <% @post.comments.each do |comment| %>
        <p><%= image_tag comment.user.get_profile_image(50,50), class: "rounded-circle" %>
           <%= comment.user.name %>
        </p>
        <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
        <% if comment.user == current_user %>
          <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete %>
        <% end %>
      <% end %>
    </div>
    <div>
        <%= form_with model: [@post, @comment] do |f| %>
          <%= f.text_area :comment, rows: '3', placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
    </div>
    
  </div>