config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: "admin/admins/sessions",
  }
  
  namespace :admin do
    root to: "dashboards#top"
    resources :users, only: [:index, :destroy]
    resources :categories, only: [:index, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    devise_for :users, skip: [:password], controllers: {
      sessions: "public/users/sessions",
      registrations: "public/users/registrations",
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :posts do
      collection do
        resources :ranks, only: [:index]
      end
      resources :comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    resources :animals, only: [:show, :edit, :update, :new, :create, :destroy]

    resources :users, only: [:index, :show] do
      resources :animals, only: [:index]
      resources :favorites, only: [:index]
      resource :relationships, only: [:create, :destroy]
      # resources :following_users, only: [:index]
      # resources :followed_users, only: [:index]
      get "following_users" => "relationships#following", as: "following"
      get "followed_users" => "relationships#followed", as: "followed"
    end

    resources :categories, only: [:create, :index, :show]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :animals
  has_many :category_posts, through: :animals, source: :posts

  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }

  scope :name_search, -> (name) do
    where("name LIKE ?", "%#{sanitize_sql_like(name)}%")
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  
  def index
    @categories = Category.all.page(params[:page])
    if params[:name].present?
      @categories = @categories.name_search(params[:name])
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
  
  def destroy
    category = Category.find(params[:id])
    category.destroy!
    redirect_to admin_categories_path, notice: "カテゴリーを削除しました。"
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      @categories = Category.all
      render :index
    end
  end
  
  def index
    @category = Category.new
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @posts = @category.category_posts
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h2>カテゴリー編集</h2>
<% if @category.errors.any? %>
  <%= @category.errors.count %>件のエラーが発生しました
  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @category do |f| %>
  <p>カテゴリー名：<%= f.text_field :name %></p>
  <%= f.submit "保存" %>
<% end %>

<p>
  <%= link_to "戻る", categories_path %>
</p>

app/views/categories/index.html.erb
<h2>カテゴリー</h2>
<% if @category.errors.any? %>
  <%= @category.errors.count %>件のエラーが発生しました
  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @category do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "新規登録" %>
<% end %>

<% @categories.each do |category| %>
  <p>
    <%= link_to category_path(category) do %>
    <%= category.name %>
    <% end %>
    <%= link_to "編集", edit_category_path(category) %>
  </p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %>の投稿一覧</h1>

<% if @posts.present? %>
  <%= render 'posts/list', posts: @posts %>
<% else %>
  <%= flash.now[:notice] %>
<% end %>

<%= link_to "戻る", categories_path %>